spring:
  application:
    name: e-cloud
  servlet:
    multipart:
      #       单文件请求最大10MB
      max-file-size: 10MB
      #       单次请求最大100MB
      max-request-size: 100MB
  # 开发,关闭缓存
  thymeleaf:
    cache: false

server:
  port: 8001

